// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package tagSearchService

import (
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

var GoUnusedProtection__ int

type Range struct {
	StartUid int32 `thrift:"StartUid,1,required"`
	EndUid   int32 `thrift:"EndUid,2,required"`
}

func NewRange() *Range {
	return &Range{}
}

func (p *Range) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error", p)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *Range) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 1: %s")
	} else {
		p.StartUid = v
	}
	return nil
}

func (p *Range) readField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 2: %s")
	} else {
		p.EndUid = v
	}
	return nil
}

func (p *Range) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Range"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("%T write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("%T write struct stop error: %s", err)
	}
	return nil
}

func (p *Range) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("StartUid", thrift.I32, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:StartUid: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.StartUid)); err != nil {
		return fmt.Errorf("%T.StartUid (1) field write error: %s", p)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:StartUid: %s", p, err)
	}
	return err
}

func (p *Range) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("EndUid", thrift.I32, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:EndUid: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.EndUid)); err != nil {
		return fmt.Errorf("%T.EndUid (2) field write error: %s", p)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:EndUid: %s", p, err)
	}
	return err
}

func (p *Range) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Range(%+v)", *p)
}

type UsrInfo struct {
	Uid    int32 `thrift:"Uid,1,required"`
	Weight int32 `thrift:"Weight,2,required"`
}

func NewUsrInfo() *UsrInfo {
	return &UsrInfo{}
}

func (p *UsrInfo) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error", p)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *UsrInfo) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 1: %s")
	} else {
		p.Uid = v
	}
	return nil
}

func (p *UsrInfo) readField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 2: %s")
	} else {
		p.Weight = v
	}
	return nil
}

func (p *UsrInfo) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UsrInfo"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("%T write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("%T write struct stop error: %s", err)
	}
	return nil
}

func (p *UsrInfo) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("Uid", thrift.I32, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:Uid: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.Uid)); err != nil {
		return fmt.Errorf("%T.Uid (1) field write error: %s", p)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:Uid: %s", p, err)
	}
	return err
}

func (p *UsrInfo) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("Weight", thrift.I32, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:Weight: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.Weight)); err != nil {
		return fmt.Errorf("%T.Weight (2) field write error: %s", p)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:Weight: %s", p, err)
	}
	return err
}

func (p *UsrInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UsrInfo(%+v)", *p)
}
